---
- name: Remove docker if installed from CentOS repo
  yum:
      name:
        - docker
        - docker-client
        - docker-client-latest
        - docker-common
        - docker-latest
        - docker-latest-logrotate
        - docker-logrotate
        - docker-engine
      state: removed
-   name: Install yum utils
    yum:
       name: "{{ item }}"
       state: latest

    with_items:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
-  name: Add Docker repo
   get_url:
       url: https://download.docker.com/linux/centos/docker-ce.repo
       dest: /etc/yum.repos.d/docker-ce.repo
   become: yes
 
- name: Enable Docker Edge & Test repo
  ini_file:
      dest: /etc/yum.repos.d/docer-ce.repo
      section: "{{ item }}"
      option: enabled
      value: 0
  become: yes
  with_items: ['docker-ce-test', 'docker-ce-edge']
- name: download container.io
  package:
        name: https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.13-3.2.el7.x86_64.rpm
        state: latest
  
- name: container.io
  package:
       name: containerd.io-1.2.13-3
       state: latest
  
- name: Install Docker
  package:
        name: docker-ce
        state: latest
  become: yes
- name: Start Docker service
  service:
      name: docker
      state: started
      enabled: yes
  become: yes
- name: Add user jenkins to docker group
  user:
     name: jenkins
     groups: docker
     append: yes
  become: yes
